### PR TITLE
Add collapsible leaderboard

### PR DESCRIPTION
**Pull request by bossoq**
Add collapsible leaderboard krub

Collapse
Screen Shot 2564-08-18 at 02 08 55

Expand
Screen Shot 2564-08-18 at 02 09 01

### CODE REVIEW

**Comment by Noxturnix** [comment]
@maythiwat found that `modalBody` is unhidden when the leaderboard is callapsed.
I have sent a pull request that fixes this issue. https://github.com/bossoq/popyut/pull/1


Screenshot at 2021-08-17 12-57-53

**Comment by bossoq** [comment]
Add function to separately show/hide head and body of leaderboard.
Add delay to body leaderboard 400ms to fit with slide in/out transition.

**Comment by narze** [comment]
Very nice! 🤗

By the way I see the scrollbar appears when collapsing the leaderboard. It's a minor issue though so I'll open another issue.


https://user-images.githubusercontent.com/248741/129833582-b4e49450-92a8-4623-814b-b7f886d08cba.mov

**Review by narze — APPROVED** [review]

**Comment by bossoq** [comment]
add overflow: hidden on main tag should help krub

**Pull request merged**
